Web:
    AppName: app
    Host: 8081
    Port: 127.0.0.1
    Env: debug
WS:
    addr: 0.0.0.0
    port: 8080
Zap:
    Filename:
    Compress: true                    #是否进行压缩
    TextFormat: "json"                #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
    TimePrecision: "millisecond"      #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
    MaxSize: 10                       #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
    MaxBackups: 7                     #保留旧日志最大个数
    MaxAge: 15                        #保留旧日志最大天数

Mysql:
    IsInitGlobalGormMysql: 1    # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30           # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    IsOpenReadDb: 0             # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Host: "mysql8019"
#    Host: "127.0.0.1"
    dbname: "im"
    Port: 3306
    Prefix: "tb_"   # 目前没有用到该配置项
    username: "root"
    password: "123456"
    Charset: "utf8"
    SetMaxIdleConns: 10
    SetMaxOpenConns: 128
    config: 'charset=utf8mb4&parseTime=True&loc=Local'
    #SetConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)
    #ReConnectInterval: 1     # 保留项,重连数据库间隔秒数
    #PingFailRetryTimes: 3    # 保留项,最大重连次数
redis:
    host: "redis507"
#    host: "127.0.0.1:6379"
    password: ""
    db: 0
zap:
    level: info
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true
jwt:
    secret: XXx
    expires: 48
    issuer: "IM-Server"

email:
    host: smtp.qq.com
    port: 465
    user: 2609081557@qq.com
    password: "ykiimtpfqvblebhh"
    default-from-email: 农专龙龙
    use-ssl: true
    user-tls: false


